### ISSUE TITLE
rails5.0.0.1 and exmaple 'HELLO WORLD' from homepage

### ISSUE THREAD

**Issue by urbanczykd** [rocketjob/rocketjob#11]
```
2017-01-26 16:15:24.739768 I [20521:rocketjob 009] [job:588a1a721bddc34af3004540] RocketJob::Job -- Start #perform
2017-01-26 16:15:24.739946 E [20521:rocketjob 009 worker.rb:109] [job:588a1a721bddc34af3004540] (0.039ms) RocketJob::Job -- Completed #perform -- Exception: NotImplementedError: NotImplementedError
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/rocketjob-2.1.3/lib/rocket_job/plugins/job/worker.rb:109:in `perform'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/rocketjob-2.1.3/lib/rocket_job/plugins/job/worker.rb:153:in `block (2 levels) in rocket_job_work'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/semantic_logger-3.4.1/lib/semantic_logger/base.rb:327:in `measure_internal'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/semantic_logger-3.4.1/lib/semantic_logger/base.rb:93:in `measure_info'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/rocketjob-2.1.3/lib/rocket_job/plugins/job/logger.rb:23:in `rocket_job_around_logger'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:285:in `block in halting'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:447:in `block in around'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_perform_callbacks'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/mongo_mapper-0.14.0/lib/mongo_mapper/plugins/embedded_callbacks.rb:77:in `run_callbacks'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/rocketjob-2.1.3/lib/rocket_job/plugins/job/worker.rb:150:in `block in rocket_job_work'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/rocketjob-2.1.3/lib/rocket_job/plugins/job/worker.rb:123:in `rocket_job_fail_on_exception!'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/rocketjob-2.1.3/lib/rocket_job/plugins/job/worker.rb:149:in `rocket_job_work'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/rocketjob-2.1.3/lib/rocket_job/worker.rb:362:in `block in process_available_jobs'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/semantic_logger-3.4.1/lib/semantic_logger/semantic_logger.rb:295:in `fast_tag'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/semantic_logger-3.4.1/lib/semantic_logger/base.rb:151:in `fast_tag'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/rocketjob-2.1.3/lib/rocket_job/worker.rb:361:in `process_available_jobs'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/rocketjob-2.1.3/lib/rocket_job/worker.rb:339:in `worker'
/Users/vox/.rvm/gems/ruby-2.3.3@vega/gems/rocketjob-2.1.3/lib/rocket_job/worker.rb:325:in `block (2 levels) in adjust_worker_threads'
2017-01-26 16:15:24.752733 I [20521:rocketjob 009] [job:588a1a721bddc34af3004542] RocketJob::Job -- Start #perform
```

**Comment by reidmorrison** [comment]
The RocketJob Server cannot find the code for the `HelloWorldJob`. Check that the code is accessible to the server and try restarting the server.

**Comment by urbanczykd** [comment]
thanks much for quick response will try twm morning and let know

**Comment by urbanczykd** [comment]
works like charm my mistake please close this issue :) 👍

**Comment by reidmorrison** [comment]
Glad you came right. If you run into issues feel free to ask on the Gitter support channel.
