### ISSUE TITLE
RocketJob Spawning too many thread and does not close it after complete.

### ISSUE THREAD

**Issue by emanzx** [rocketjob/rocketjob#19]
Ruby Version = ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]
Rocket Job Version = 3.5.2
Application/framework names and versions  = Rails (5.2.1.1)
Full Stack Trace, if an exception is being raised. 

> ScanJobStatefailed
ID: 5c07414844967931e5ddbb92
Duration: 1.000ms
Created At: 2018-12-05 03:08:56 UTC
Started At: 2018-12-05 03:09:09 UTC
% Complete: 0
Failed At: 2018-12-05 03:09:09 UTC
Collect Output: true
Destroy On Complete: false
Domain: zgwy.my
Domain: 209828
Failure Count: 1
Priority: 50
Worker Name: srv1:2
Exception:
{
  "_id": {
    "$oid": "5c0741554496792593868d0a"
  },
  "backtrace": [
    "/home/system/.rvm/gems/ruby-2.4.4/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:47:in `initialize'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:47:in `new'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:47:in `instantiate'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:15:in `get'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:76:in `get_thread'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:11:in `initialize'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:129:in `new'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:129:in `start'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/celluloid-0.17.3/lib/celluloid/cell.rb:43:in `initialize'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/celluloid-0.17.3/lib/celluloid.rb:195:in `new'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/celluloid-0.17.3/lib/celluloid.rb:195:in `new'",
    "/home/system/v6test/app/models/scan_job.rb:12:in `perform'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/rocketjob-3.5.2/lib/rocket_job/plugins/job/worker.rb:163:in `block (2 levels) in rocket_job_work'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.1.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/semantic_logger-4.3.1/lib/semantic_logger/base.rb:353:in `measure_internal'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/semantic_logger-4.3.1/lib/semantic_logger/base.rb:97:in `measure_info'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/rocketjob-3.5.2/lib/rocket_job/plugins/job/logger.rb:22:in `rocket_job_around_logger'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.1.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/activesupport-5.2.1.1/lib/active_support/callbacks.rb:136:in `run_callbacks'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/mongoid-7.0.2/lib/mongoid/interceptable.rb:132:in `run_callbacks'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/rocketjob-3.5.2/lib/rocket_job/plugins/job/worker.rb:161:in `block in rocket_job_work'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/rocketjob-3.5.2/lib/rocket_job/plugins/job/worker.rb:132:in `rocket_job_fail_on_exception!'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/rocketjob-3.5.2/lib/rocket_job/plugins/job/worker.rb:156:in `rocket_job_work'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/rocketjob-3.5.2/lib/rocket_job/worker.rb:111:in `block in process_available_jobs'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/semantic_logger-4.3.1/lib/semantic_logger/semantic_logger.rb:379:in `named_tagged'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/rocketjob-3.5.2/lib/rocket_job/worker.rb:110:in `process_available_jobs'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/rocketjob-3.5.2/lib/rocket_job/worker.rb:85:in `run'",
    "/home/system/.rvm/gems/ruby-2.4.4/gems/rocketjob-3.5.2/lib/rocket_job/worker.rb:52:in `block in initialize'"
  ],
  "class_name": "ThreadError",
  "message": "can't create Thread: Resource temporarily unavailable",
  "record_number": null,
  "worker_name": "srv1:2"
 }

### Expected Behavior

RocketJob should not spawn thread beyond limit 

### Actual Behavior

Rocketjob is spawning thread untill it out of resource. and what I notice is the thread count is equal to the completed job. seem like it run the job but once the job is done the thread is not closed thus the number of thread is increasing until it exhaust it self and only restore back to normal if I restart rocket job process.

**Comment by emanzx** [comment]
Found the error.. it in my code.. sorry for the inconvenience..
